Repository livable-final/server, pull requests merged in 2023-09, with the labels that each got.

#18 개발, 운영, 테스트 환경 분리 완료
  .gitignore
  src/main/java/com/livable/server/entity/Menu.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: setting

#26 최신 리뷰 리스트 응답 기능 구현 완료
  src/main/java/com/livable/server/review/controller/.gitkeep
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/.gitkeep
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/.gitkeep
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepository.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepositoryImpl.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewRepository.java
  src/main/java/com/livable/server/review/service/.gitkeep
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: develop

#30 분리된 도메인 로직 통합 완료
  src/main/java/com/livable/server/invitation/repository/InvitationRepository.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepository.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/livable/server/reservation/repository/ReservationRepository.java
  src/main/java/com/livable/server/visitation/service/InvitationService.java
  src/main/java/com/livable/server/visitation/service/VisitationFacadeService.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
  src/test/java/com/livable/server/visitation/service/InvitationServiceTest.java
  src/test/java/com/livable/server/visitation/service/VisitationFacadeServiceTest.java
Labels: refactor

#39 초대장 저장 기능 구현 완료 (알림톡 기능 추가 전)
  src/main/java/com/livable/server/entity/InvitationPurpose.java
  src/main/java/com/livable/server/invitation/controller/InvitationController.java
  src/main/java/com/livable/server/invitation/domain/InvitationErrorCode.java
  src/main/java/com/livable/server/invitation/domain/InvitationPurpose.java
  src/main/java/com/livable/server/invitation/domain/InvitationValidationMessage.java
  src/main/java/com/livable/server/invitation/dto/InvitationRequest.java
  src/main/java/com/livable/server/invitation/repository/InvitationReservationMapRepository.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepository.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepositoryImpl.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: develop

#35 특정 메뉴의 리뷰 리스트 응답 기능 구현 완료
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepository.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepositoryImpl.java
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: develop

#34 Invitation Repository Query Test 구현 및 QR 도메인 로직 리팩토링 완료
  src/main/java/com/livable/server/invitation/dto/InvitationDetailTimeDto.java
  src/main/java/com/livable/server/invitation/repository/InvitationRepository.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/visitation/dto/VisitationResponse.java
  src/main/java/com/livable/server/visitation/service/VisitationFacadeService.java
  src/test/java/com/livable/server/invitation/repository/InvitationRepositoryTest.java
  src/test/java/com/livable/server/visitation/mock/MockInvitationDetailTimeDto.java
  src/test/java/com/livable/server/visitation/service/InvitationServiceTest.java
  src/test/java/com/livable/server/visitation/service/VisitationFacadeServiceTest.java
Labels: enhancement, refactor

#37 주차등록 API 컨트롤러 및 테스트 구현 완료
  src/main/java/com/livable/server/entity/ParkingLog.java
  src/main/java/com/livable/server/invitation/domain/InvitationValidationGuideMessage.java
  src/main/java/com/livable/server/visitation/controller/VisitationController.java
  src/main/java/com/livable/server/visitation/domain/VisitationErrorCode.java
  src/main/java/com/livable/server/visitation/dto/VisitationRequest.java
  src/main/java/com/livable/server/visitation/repository/ParkingLogRepository.java
  src/main/java/com/livable/server/visitation/service/ParkingLogService.java
  src/main/java/com/livable/server/visitation/service/VisitationFacadeService.java
  src/main/java/com/livable/server/visitation/service/VisitorService.java
  src/test/java/com/livable/server/visitation/controller/VisitationControllerTest.java
  src/test/java/com/livable/server/visitation/dto/VisitationRequestTest.java
  src/test/java/com/livable/server/visitation/mock/MockRegisterParkingDto.java
  src/test/java/com/livable/server/visitation/repository/ParkingLogRepositoryTest.java
  src/test/java/com/livable/server/visitation/service/ParkingLogServiceTest.java
  src/test/java/com/livable/server/visitation/service/VisitationFacadeServiceTest.java
Labels: develop

#49 Amazon S3 적용 및 이미지 저장 기능 구현 완료
  build.gradle
  src/main/java/com/livable/server/core/config/S3Config.java
  src/main/java/com/livable/server/core/util/S3Uploader.java
Labels: develop

#56 초대장 상세 응답 기능 구현 완료
  src/main/java/com/livable/server/invitation/controller/InvitationController.java
  src/main/java/com/livable/server/invitation/domain/InvitationErrorCode.java
  src/main/java/com/livable/server/invitation/dto/InvitationProjection.java
  src/main/java/com/livable/server/invitation/dto/InvitationResponse.java
  src/main/java/com/livable/server/invitation/repository/InvitationQueryRepository.java
  src/main/java/com/livable/server/invitation/repository/InvitationQueryRepositoryImpl.java
  src/main/java/com/livable/server/invitation/repository/InvitationRepository.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepository.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepositoryImpl.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: develop

#59 달력 리뷰 상세페이지 응답 기능 구현 완료
  src/main/java/com/livable/server/review/controller/MyReviewController.java
  src/main/java/com/livable/server/review/domain/.gitkeep
  src/main/java/com/livable/server/review/domain/MyReview.java
  src/main/java/com/livable/server/review/domain/MyReviewErrorCode.java
  src/main/java/com/livable/server/review/dto/MyReviewProjection.java
  src/main/java/com/livable/server/review/dto/MyReviewResponse.java
  src/main/java/com/livable/server/review/repository/MyReviewRepository.java
  src/main/java/com/livable/server/review/repository/MyReviewRepositoryImpl.java
  src/main/java/com/livable/server/review/service/MyReviewService.java
  src/test/java/com/livable/server/review/controller/MyReviewControllerTest.java
  src/test/java/com/livable/server/review/domain/MyReviewTest.java
  src/test/java/com/livable/server/review/service/MyReviewServiceTest.java
Labels: develop

#61 마이페이지 데이터 응답 구현 완료
  src/main/java/com/livable/server/member/controller/.gitkeep
  src/main/java/com/livable/server/member/controller/MemberController.java
  src/main/java/com/livable/server/member/domain/MemberErrorCode.java
  src/main/java/com/livable/server/member/dto/.gitkeep
  src/main/java/com/livable/server/member/dto/MemberResponse.java
  src/main/java/com/livable/server/member/dto/MyPageProjection.java
  src/main/java/com/livable/server/member/exception/.gitkeep
  src/main/java/com/livable/server/member/repository/.gitkeep
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/member/service/.gitkeep
  src/main/java/com/livable/server/member/service/MemberService.java
  src/test/java/com/livable/server/member/controller/MemberControllerTest.java
  src/test/java/com/livable/server/member/service/MemberServiceTest.java
Labels: develop

#64 초대장 수정, 삭제 기능 구현 완료
  src/main/java/com/livable/server/entity/Invitation.java
  src/main/java/com/livable/server/invitation/controller/InvitationController.java
  src/main/java/com/livable/server/invitation/domain/InvitationErrorCode.java
  src/main/java/com/livable/server/invitation/dto/InvitationRequest.java
  src/main/java/com/livable/server/invitation/repository/InvitationQueryRepository.java
  src/main/java/com/livable/server/invitation/repository/InvitationQueryRepositoryImpl.java
  src/main/java/com/livable/server/invitation/repository/InvitationReservationMapRepository.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/visitation/repository/ParkingLogRepository.java
  src/main/java/com/livable/server/visitation/repository/VisitorRepository.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: develop

#68 홈 화면에 필요한 정보 응답 기능 구현 완료
  src/main/java/com/livable/server/home/controller/HomeController.java
  src/main/java/com/livable/server/home/dto/HomeResponse.java
  src/main/java/com/livable/server/member/domain/MemberErrorCode.java
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/member/service/MemberService.java
  src/test/java/com/livable/server/home/controller/HomeControllerTest.java
  src/test/java/com/livable/server/member/service/MemberServiceTest.java
Labels: develop

#70 초대장 기능 리펙토링 완료
  src/main/java/com/livable/server/invitation/dto/InvitationResponse.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/main/java/com/livable/server/reservation/repository/ReservationQueryRepositoryImpl.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: refactor

#73 Merge 과정중 충돌된 부분 해결 완료
  src/main/java/com/livable/server/member/domain/MemberErrorCode.java
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/member/service/MemberService.java
Labels: bug

#67 오점완 리뷰 상세 페이지 응답 기능 구현 완료
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/Projection.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepository.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewCustomRepositoryImpl.java
  src/main/java/com/livable/server/review/service/MyReviewService.java
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: develop

#78 JWT 라이브러리 추가 및 토큰 기능 구현 완료
  build.gradle
  src/main/java/com/livable/server/core/util/ActorType.java
  src/main/java/com/livable/server/core/util/JwtTokenProvider.java
  src/test/java/com/livable/server/core/util/JwtTokenProviderTest.java
Labels: develop

#81 초대 목록 응답 리펙토링 완료
  src/main/java/com/livable/server/invitation/controller/InvitationController.java
  src/main/java/com/livable/server/invitation/service/InvitationService.java
Labels: refactor

#84 포인트 목표 달성 데이터 응답 구현 완료
  src/main/java/com/livable/server/point/controller/.gitkeep
  src/main/java/com/livable/server/point/controller/PointController.java
  src/main/java/com/livable/server/point/domain/DateFactory.java
  src/main/java/com/livable/server/point/domain/DateRange.java
  src/main/java/com/livable/server/point/domain/PointErrorCode.java
  src/main/java/com/livable/server/point/dto/.gitkeep
  src/main/java/com/livable/server/point/dto/PointResponse.java
  src/main/java/com/livable/server/point/exception/.gitkeep
  src/main/java/com/livable/server/point/repository/.gitkeep
  src/main/java/com/livable/server/point/repository/PointRepository.java
  src/main/java/com/livable/server/point/service/.gitkeep
  src/main/java/com/livable/server/point/service/PointService.java
  src/test/java/com/livable/server/point/controller/PointControllerTest.java
  src/test/java/com/livable/server/point/domain/DateFactoryTest.java
  src/test/java/com/livable/server/point/domain/DateRangeTest.java
  src/test/java/com/livable/server/point/service/PointServiceTest.java
Labels: develop

#92 JWT 토큰 적용 완료
  build.gradle
  src/main/java/com/livable/server/core/config/WebConfig.java
  src/main/java/com/livable/server/core/util/Actor.java
  src/main/java/com/livable/server/core/util/ActorType.java
  src/main/java/com/livable/server/core/util/JwtTokenProvider.java
  src/main/java/com/livable/server/core/util/LoginActor.java
  src/main/java/com/livable/server/core/util/LoginActorArgumentResolver.java
  src/main/java/com/livable/server/home/controller/HomeController.java
  src/main/java/com/livable/server/invitation/controller/InvitationController.java
  src/main/java/com/livable/server/member/controller/MemberController.java
  src/main/java/com/livable/server/member/domain/MemberErrorCode.java
  src/main/java/com/livable/server/point/controller/PointController.java
  src/main/java/com/livable/server/reservation/controller/ReservationController.java
  src/main/java/com/livable/server/restaurant/controller/RestaurantController.java
  src/main/java/com/livable/server/review/controller/MyReviewController.java
  src/main/java/com/livable/server/visitation/controller/VisitationController.java
  src/test/java/com/livable/server/core/util/JwtTokenProviderTest.java
  src/test/java/com/livable/server/core/util/TestConfig.java
  src/test/java/com/livable/server/home/controller/HomeControllerTest.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
  src/test/java/com/livable/server/member/controller/MemberControllerTest.java
  src/test/java/com/livable/server/point/controller/PointControllerTest.java
  src/test/java/com/livable/server/reservation/controller/ReservationControllerTest.java
  src/test/java/com/livable/server/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/livable/server/review/controller/MyReviewControllerTest.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/visitation/controller/VisitationControllerTest.java
Labels: develop, refactor

#96 프로젝트 시간 서버와 맞추기 완료
  src/main/java/com/livable/server/LivableServerApplication.java
  src/main/resources/application.yml
Labels: develop, setting

#87 회원 출입카드 정보 응답 구현
  src/main/java/com/livable/server/home/controller/HomeController.java
  src/main/java/com/livable/server/home/dto/HomeResponse.java
  src/main/java/com/livable/server/member/domain/MemberErrorCode.java
  src/main/java/com/livable/server/member/dto/AccessCardProjection.java
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/member/service/MemberService.java
  src/test/java/com/livable/server/home/controller/HomeControllerTest.java
  src/test/java/com/livable/server/member/service/MemberServiceTest.java
Labels: develop

#89 홈 화면 정보 버그 수정
  src/main/java/com/livable/server/home/controller/HomeController.java
  src/main/java/com/livable/server/home/dto/HomeResponse.java
  src/main/java/com/livable/server/member/dto/BuildingInfoProjection.java
  src/main/java/com/livable/server/member/repository/MemberRepository.java
  src/main/java/com/livable/server/member/service/MemberService.java
  src/test/java/com/livable/server/home/controller/HomeControllerTest.java
  src/test/java/com/livable/server/member/service/MemberServiceTest.java
Labels: bug

#98 룰렛에 사용되는 카테고리, 메뉴 목록 응답
  src/main/java/com/livable/server/menu/controller/.gitkeep
  src/main/java/com/livable/server/menu/controller/MenuController.java
  src/main/java/com/livable/server/menu/domain/MenuErrorCode.java
  src/main/java/com/livable/server/menu/dto/.gitkeep
  src/main/java/com/livable/server/menu/dto/MenuResponse.java
  src/main/java/com/livable/server/menu/dto/RouletteMenu.java
  src/main/java/com/livable/server/menu/dto/RouletteMenuProjection.java
  src/main/java/com/livable/server/menu/repository/.gitkeep
  src/main/java/com/livable/server/menu/repository/MenuRepository.java
  src/main/java/com/livable/server/menu/service/.gitkeep
  src/main/java/com/livable/server/menu/service/MenuService.java
  src/test/java/com/livable/server/menu/controller/MenuControllerTest.java
  src/test/java/com/livable/server/menu/service/MenuServiceTest.java
Labels: develop

#101 최신 리뷰 리스트 응답 기능 개선 완료
  src/main/java/com/livable/server/core/util/ImageSeparator.java
  src/main/java/com/livable/server/core/util/S3Uploader.java
  src/main/java/com/livable/server/entity/ReviewImage.java
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/Projection.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewProjection.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/MyReviewRepository.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewProjectionRepository.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewRepository.java
  src/main/java/com/livable/server/review/repository/querydsl/MyReviewQueryDslRepository.java
  src/main/java/com/livable/server/review/repository/querydsl/MyReviewQueryDslRepositoryImpl.java
  src/main/java/com/livable/server/review/repository/querydsl/RestaurantReviewQueryDslRepository.java
  src/main/java/com/livable/server/review/repository/querydsl/RestaurantReviewQueryDslRepositoryImpl.java
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/core/util/ImageSeparatorTest.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/MyReviewServiceTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: enhancement, develop

#105 특정 음식점에 대한 리뷰 리스트 응답 기능 구현 완료
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewProjectionRepository.java
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: develop

#102 방문증 인증 callback 구현 완료
  src/main/java/com/livable/server/invitation/controller/InvitationValidationController.java
  src/main/java/com/livable/server/invitation/service/InvitationValidationService.java
  src/test/java/com/livable/server/invitation/controller/InvitationValidationControllerTest.java
  src/test/java/com/livable/server/invitation/service/InvitationValidationServiceTest.java
Labels: develop

#107 관리자 페이지 목록 응답 구현 완료
  src/main/java/com/livable/server/admin/controller/AdminController.java
  src/main/java/com/livable/server/admin/domain/AdminErrorCode.java
  src/main/java/com/livable/server/admin/domain/VisitationQuery.java
  src/main/java/com/livable/server/admin/domain/VisitationQueryCondition.java
  src/main/java/com/livable/server/admin/dto/AdminResponse.java
  src/main/java/com/livable/server/admin/repository/AdminQueryRepository.java
  src/main/java/com/livable/server/admin/repository/AdminQueryRepositoryImpl.java
  src/main/java/com/livable/server/admin/repository/AdminRepository.java
  src/main/java/com/livable/server/admin/service/AdminService.java
  src/main/java/com/livable/server/core/util/ActorType.java
  src/main/java/com/livable/server/core/util/JwtTokenProvider.java
  src/main/java/com/livable/server/entity/Admin.java
Labels: develop

#111 룰렛에 사용되는 카테고리, 메뉴 목록 응답 쿼리 수정
  src/main/java/com/livable/server/menu/repository/MenuRepository.java
Labels: bug

#114 오점완 리뷰 쓰기 기능 구현, S3uploader 기능 추가
  src/main/java/com/livable/server/core/util/S3Uploader.java
  src/main/java/com/livable/server/review/controller/ReviewController.java
  src/main/java/com/livable/server/review/domain/ReviewErrorCode.java
  src/main/java/com/livable/server/review/domain/ReviewSelectType.java
  src/main/java/com/livable/server/review/dto/ReviewRequest.java
  src/main/java/com/livable/server/review/repository/ReviewImageRepository.java
  src/main/java/com/livable/server/review/repository/ReviewRepository.java
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: develop

#126 목표 달성 포인트 지급 기능 구현 완료
  src/main/java/com/livable/server/entity/Point.java
  src/main/java/com/livable/server/entity/PointCode.java
  src/main/java/com/livable/server/point/controller/PointController.java
  src/main/java/com/livable/server/point/domain/DateFactory.java
  src/main/java/com/livable/server/point/domain/PointAchievement.java
  src/main/java/com/livable/server/point/domain/PointErrorCode.java
  src/main/java/com/livable/server/point/dto/PointProjection.java
  src/main/java/com/livable/server/point/dto/PointResponse.java
  src/main/java/com/livable/server/point/repository/PointLogRepository.java
  src/main/java/com/livable/server/point/repository/PointRepository.java
  src/main/java/com/livable/server/point/service/PointService.java
Labels: develop

#128 포인트 서비스 테스트 코드 수정 누락으로 인한 빌드 실패 수정 완료
  src/test/java/com/livable/server/point/service/PointServiceTest.java
Labels: hotfix

#125 메뉴를 판매하는 식당 목록 응답 구현 완료
  src/main/java/com/livable/server/entity/Restaurant.java
  src/main/java/com/livable/server/restaurant/controller/RestaurantController.java
  src/main/java/com/livable/server/restaurant/domain/RestaurantErrorCode.java
  src/main/java/com/livable/server/restaurant/dto/RestaurantByMenuProjection.java
  src/main/java/com/livable/server/restaurant/dto/RestaurantResponse.java
  src/main/java/com/livable/server/restaurant/repository/RestaurantGroupByMenuProjectionRepository.java
  src/main/java/com/livable/server/restaurant/service/RestaurantService.java
  src/test/java/com/livable/server/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/livable/server/restaurant/mock/MockRestaurantByMenuDto.java
  src/test/java/com/livable/server/restaurant/service/RestaurantServiceTest.java
Labels: develop

#138 포인트, 마이페이지 관련 기능에 JWT 적용 완료
  src/main/java/com/livable/server/point/controller/PointController.java
  src/main/java/com/livable/server/point/service/PointService.java
Labels: enhancement

#141 모든 음식점, 특정 메뉴의 음식점 리뷰 리스트 응답 기능 개선 완료
  src/main/java/com/livable/server/entity/ReviewImage.java
  src/main/java/com/livable/server/review/controller/RestaurantReviewController.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewProjection.java
  src/main/java/com/livable/server/review/dto/RestaurantReviewResponse.java
  src/main/java/com/livable/server/review/repository/RestaurantReviewProjectionRepository.java
  src/main/java/com/livable/server/review/service/RestaurantReviewService.java
  src/test/java/com/livable/server/review/controller/RestaurantReviewControllerTest.java
  src/test/java/com/livable/server/review/service/RestaurantReviewServiceTest.java
Labels: document

#143 Test Properties 적용 완료
  .gitignore
  src/test/java/com/livable/server/LivableServerApplicationTests.java
  src/test/java/com/livable/server/core/util/TestProperties.java
Labels: develop, setting

#150 초대장 저장 리펙토링 완료
  src/main/java/com/livable/server/invitation/domain/InvitationPurpose.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
  src/test/java/com/livable/server/invitation/repository/InvitationRepositoryTest.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: refactor

#153 음식점에서 판매하는 메뉴 응답 리스트 기능 구현
  src/main/java/com/livable/server/restaurant/controller/RestaurantController.java
  src/main/java/com/livable/server/restaurant/dto/RestaurantResponse.java
  src/main/java/com/livable/server/restaurant/repository/RestaurantCustomRepository.java
  src/main/java/com/livable/server/restaurant/repository/RestaurantCustomRepositoryImpl.java
  src/main/java/com/livable/server/restaurant/service/RestaurantService.java
Labels: develop

#159 목표 달성 포인트 획득 기능 개선 완료
  src/main/java/com/livable/server/entity/PointLog.java
  src/main/java/com/livable/server/point/dto/PointProjection.java
  src/main/java/com/livable/server/point/repository/PointLogRepository.java
  src/main/java/com/livable/server/point/repository/PointRepository.java
  src/main/java/com/livable/server/point/service/PointService.java
  src/test/java/com/livable/server/point/service/PointServiceTest.java
Labels: enhancement

#161 invitation commonPlaceId 가져오는 로직 주석 처리
  src/main/java/com/livable/server/invitation/service/InvitationService.java
Labels: bug

#164 초대장 수정 장소 변경에 대한 추가 로직 구현 및 테스트 추가 완료
  src/main/java/com/livable/server/invitation/service/InvitationService.java
  src/test/java/com/livable/server/invitation/service/InvitationServiceTest.java
Labels: develop
