Repository livable-final/server, pull requests merged in 2023-10, with the labels that each got.

#166 포인트 로그 도메인 개선 완료
  src/main/java/com/livable/server/entity/PointLog.java
Labels: enhancement

#168 음식점 검색 기능 구현
  src/main/java/com/livable/server/restaurant/controller/RestaurantController.java
  src/main/java/com/livable/server/restaurant/dto/RestaurantResponse.java
  src/main/java/com/livable/server/restaurant/repository/RestaurantCustomRepository.java
  src/main/java/com/livable/server/restaurant/repository/RestaurantCustomRepositoryImpl.java
  src/main/java/com/livable/server/restaurant/service/RestaurantService.java
Labels: develop

#172 포인트 로그 개선에 따른 목표 달성 포인트 지급 서비스 수정 완료
  src/main/java/com/livable/server/entity/PointLog.java
  src/main/java/com/livable/server/point/domain/PointErrorCode.java
  src/main/java/com/livable/server/point/repository/PointLogRepository.java
  src/main/java/com/livable/server/point/service/PointService.java
  src/test/java/com/livable/server/point/service/PointServiceTest.java
Labels: enhancement

#173 오점완 달력 데이터 기능 구현
  src/main/java/com/livable/server/entity/Review.java
  src/main/java/com/livable/server/review/controller/ReviewController.java
  src/main/java/com/livable/server/review/dto/ReviewResponse.java
  src/main/java/com/livable/server/review/repository/ReviewProjectionRepository.java
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: develop

#181 리뷰 상세데이터를 포함한 오점완 달력 데이터 응답 기능 구현 완료
  src/main/java/com/livable/server/entity/Review.java
  src/main/java/com/livable/server/review/controller/ReviewController.java
  src/main/java/com/livable/server/review/dto/Projection.java
  src/main/java/com/livable/server/review/dto/ReviewResponse.java
  src/main/java/com/livable/server/review/repository/ReviewProjectionRepository.java
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: develop

#187 가장 많이 선택한 메뉴 10위까지 응답, 메뉴를 판매하는 식당 목록 응답 EndPoint 수정
  src/main/java/com/livable/server/menu/controller/MenuController.java
  src/main/java/com/livable/server/restaurant/controller/RestaurantController.java
  src/test/java/com/livable/server/menu/controller/MenuControllerTest.java
  src/test/java/com/livable/server/restaurant/controller/RestaurantControllerTest.java
Labels: refactor

#192 목표 달성 포인트 지급 단위 테스트 구현 완료
  src/test/java/com/livable/server/point/controller/PointControllerTest.java
  src/test/java/com/livable/server/point/service/PointServiceTest.java
Labels: test

#193 초대장 저장 유효성 검사 추가 완료
  src/main/java/com/livable/server/invitation/domain/InvitationValidationMessage.java
  src/main/java/com/livable/server/invitation/dto/InvitationRequest.java
  src/test/java/com/livable/server/invitation/controller/InvitationControllerTest.java
Labels: develop

#195 리뷰 포인트 기능 구현 완료
  src/main/java/com/livable/server/menu/repository/MenuRepository.java
  src/main/java/com/livable/server/point/repository/PointLogRepository.java
  src/main/java/com/livable/server/review/domain/PointReview.java
  src/main/java/com/livable/server/review/dto/MenuRequest.java
  src/main/java/com/livable/server/review/dto/ReviewRequest.java
  src/main/java/com/livable/server/review/repository/ReviewMenuMapRepository.java
  src/main/java/com/livable/server/review/repository/ReviewRepository.java
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: develop

#196 리뷰 상세데이터를 포함한 오점완 달력 데이터 응답 기능 개선 완료
  src/main/java/com/livable/server/entity/Review.java
  src/main/java/com/livable/server/review/dto/Projection.java
  src/main/java/com/livable/server/review/dto/ReviewResponse.java
  src/main/java/com/livable/server/review/repository/ReviewProjectionRepository.java
Labels: enhancement

#200 Hotfix: 리뷰 이미지 요청 오류 해결 (#199)
  src/main/java/com/livable/server/review/controller/ReviewController.java
Labels: hotfix

#202 리뷰 하루 작성 하나로 변경 사항 수정 완료
  src/main/java/com/livable/server/review/domain/ReviewErrorCode.java
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: modify

#204 Docs: Readme 1차 작성 완료
  README.md
Labels: document

#208 리뷰 작성 이미지 저장 로직 수정 (#207)
  src/main/java/com/livable/server/review/service/ReviewService.java
Labels: hotfix

#212 리드미 작성 완료
  README.md
Labels: develop
